baseURL = "https://ilugc.in/"
languageCode = "en-us"
title = "ILUGC"
theme = "mainroad"
enableRobotsTXT = true

[Params]
    opengraph = true
    readmore = false
    leftsidebar = false
    authorbox = false
    post_meta = ["author", "date"]
    mainSections = ["post"]

[Params.logo]
  title = "ILUGC"
  subtitle = "Indian Linux User's Group - Chennai (Madras)"

[Params.sidebar]
  home = "right"
  list = "right"
  single = false
  # Enable widgets in given order
  widgets = ["search", "recent"]

[[menu.main]]
	name = "About"
	url = "/about/"
	weight = 10

[[menu.main]]
	name = "Chat"
	url = "/chat/"
	weight = 30

[[menu.main]]
	name = "Getting Started in FOSS"
	url = "/getting-started/"
	weight = 50

[[menu.main]]
	name = "Get Involved with ILUGC"
	url = "/get-involved/"
	weight = 60

[[menu.main]]
	name = "Contact"
	url = "/contact/"
	weight = 20

[[menu.main]]
	name = "FAQ"
	url = "/faq/"
	weight = 40
